### ISSUE TITLE
`npx create-dao` doesn't work on Windows

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/create-dao#12]
When trying to run the CLI from Windows, I see this error:

```bash
$ npx create-dao
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn create-next-app ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn create-next-app',
  path: 'create-next-app',
  spawnargs: [
    '--example=https://github.com/Developer-DAO/create-dao/tree/main/template'
  ]
}
```

OS version: Windows 11
Terminal: Git-bash
Node version: 14.18.1

**Comment by miralsuthar** [comment]
![image](https://user-images.githubusercontent.com/57826091/143778772-9c0f5707-fa68-4d93-aae9-331a18785626.png)
I am also getting the same error in windows.

**Comment by AlmostEfficient** [comment]
Getting the same on Windows 10 build 19043, NodeJs version 16.

**Comment by Dhaiwat10** [comment]
Closing via #17
